<a href="https://colab.research.google.com/github/QCSG-Qiskit/Colab-for-QML/blob/main/Numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##모듈과 패키지

In [1]:
#모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
#패키지는 여러 모듈을 묶은 것 (폴더)  단순하게 위는 파일이고 아래는 폴더임. 폴더를 패키지라 표현
#import 모듈.  모듈을 불러옴
#import 모듈1, 모듈2
#모듈.변수
#모듈.함수() 모듈이 쭉 담고 있는 것을 불러오는 것임
#모듈.클래스()
#import my
#my.a + my.b
#my.b
#bot.1=my.Robot
#my.add() 이런식으로 쓸 수 있음
#my.py 이 폴더에 이런게 적혀 있다고 보자
#a=1
#b=2
#class Robot()
#def add(a,b)

In [4]:
import math #math라는 모듈임. 같이 딸려서 깔림 colab이 깔려 있어서 좋음. torch는 깔아야 함. colab은 구글 컴퓨터를 쓰기 때문에 쓸 수가 있음
print(math.pi)
#print(pi) 그냥 pi는 없음 cos, sin도 없음. matlab은 있지만..
print(math.sqrt(4)) #sqrt는 제곱근 구해짐

3.141592653589793
2.0


In [6]:
import math as m
print(m.pi)
print(m.sqrt(4)) #math를 m으로 부를 수 있음

3.141592653589793
2.0


In [8]:
from math import pi, sqrt
print(pi)
print(sqrt(4)) #math.pi는 오히려 안됨

3.141592653589793
2.0


In [11]:
from math import * # *이 all이란 뜻
print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [14]:
from math import sqrt as s
print(s(4))

2.0


In [17]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [18]:
#import 패키지
#import 패키지.모듈 #패키지가 여러가지 파일을 가지고 있고, 그걸 import하면 쩜 해서 사용 할 수 있음
#import 패키지.모듈1, 패키지.모듈2
#패키지.모듈.변수
#패키지.모듈.함수()
#패키지.모듈.클래스()
#폴더 -> 파일 - >함수를 연다는 뜻임

In [21]:
import numpy as np #numpy는 라이브러리라고 해서 패키지와 모듈들을 모아놓음. 폴더 위에 폴더임. (numerical python이어서 numpy임)
a=np.array([1,2,3]) #array함수 속에다가 1,2,3이라는 list를 넣어준 것임.
print(a)

[1 2 3]


In [27]:
import numpy.random
print(numpy.random.randn(3,3)) #Normal distribution, (3,3)은 3행 3열 짜리를 의미

[[-0.99744173 -0.90088041  0.40859998]
 [-0.12240256  1.06118396 -1.72066911]
 [-0.53876083  0.71756872  1.63008701]]


In [29]:
import numpy.random as nr
print(nr.randn(3,3))

[[ 1.47808454  0.08831133 -0.15104542]
 [-0.25279429  0.5095186   0.39814661]
 [ 1.84625972  1.32852799 -0.91173926]]


In [31]:
from numpy.random import randn
print(randn(3,3))

[[-0.76718815 -1.11940892  1.06691124]
 [ 2.09098616  0.02666174  0.00249263]
 [-0.57498724  0.20731335 -0.48363262]]


In [34]:
from numpy.random import *
print(rand(3,3)) #rand는 uniform distribution.음 0과 1에이 균등분포에서 샘플링해옴

[[0.59562019 0.43971029 0.49285735]
 [0.3552663  0.31318416 0.22476134]
 [0.92691001 0.38414401 0.84186366]]


In [36]:
from numpy.random import randn as rn
print(rn(3,3))

[[ 0.53911615  0.66281833  0.03443652]
 [-0.8086671   0.06702322  0.06255777]
 [-0.58123631  1.52921813 -0.1526921 ]]


In [38]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[-1.12633347  0.94635722  0.43752597]
 [ 0.42343916 -1.71160479  0.80152427]
 [ 1.4348371   0.15304735  0.98780681]]
[[0.14259588 0.24409199 0.43412008]
 [0.04827409 0.91928115 0.48527446]
 [0.19827883 0.4514574  0.6204364 ]]


##numpy 본격적으로

In [48]:
import numpy as np
a=np.array([1,2,3,4]) #배열을 만들어주는 것. list는 입력으로 들어가는 함수인데 이거랑 다름
print(a)
print(type(a))
print(a.dtype) #a.dtype은 data type. a인스턴스가 가지고 있는 attribute임. 왜 위가아함수가 아니고 클래스지. a.이 되려면 struct라 봐야하나. 이 안에서 클래스를 가지고 뱉었을 수도
print(a.shape) #.shape은 80살까지 쓸 것. 숫자 하나 써 있으면 무차원. 네 개가 있으니까 4,가 쓰임
b=np.array([1,2,3.1,4])
print(b.dtype) #하나만 float으로 바뀔 수가 없어서 네 개가 전부 float로 바뀜 #하나라도 실수면 자동으로 실수 타입으로 바꿔줌
print(type(b[0])) #한 숫자에 64인 것임.

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64
<class 'numpy.float64'>


In [52]:
a=np.array(2**64-1) #python은 overflow안 남. 알아서 unit로 바꿔줌. 한 숫자가 몇 기가가 될때까지도 다이나믹하게 데이터를 assign함
print(a)
a.dtype

18446744073709551615


dtype('uint64')

In [61]:
A=np.array([[1,2],[3,4]]) # 이 셀부터는 import numpy as np는 실행 했다 치고 작성
#A=np.array([[1,2],[3,4,5]]) #여기부터는 행렬 개념이 들어감, 행렬이어서 각 행에 해당하는 숫자의 개수가 같아야 함. 사이즈가 안 맞으면 에러가 뜸
print(A)
print(A.shape) #제일 중요한 게 shape
print(A.ndim) # 차원의 수
print(A.size) # 전체 성분의 수
a.size == A.shape[0]*A.shape[1]

[[1 2]
 [3 4]]
(2, 2)
2
4


False

In [76]:
print(np.zeros(5))
print(np.zeros_like(A)) #A에 맞게 가져가서 0으로 채워줌
print(np.ones(5))
print(np.zeros((3,3))) #리스트나 튜플로 묶어서 줘라. 하나로 줘야함. #튜플을 입력으로! 그냥 np.zeros(3,3) 으로 만들면 안됨.
import torch
print(torch.zeros((3,3)))
print(np.arange(3,10,2)) #array이라서 arange 임. range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) #소수점 가능
print(np.linspace(0,1,10, endpoint=False)) # 0에서부터 1포함 10개로 쪼개는 것. endpoint 포함하는 게 디폴트임. 포함하지 않는 게 False로 해야함

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [79]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c = a + b
print(c) #드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴!
[1,2,3]+[4,5,6]


[5 7 9]


[1, 2, 3, 4, 5, 6]

In [88]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[4,5,6],[1,1,1]])
C = A+B
D = A-B
print(C)
print(D)
print()
print(A*B) #곱셈은? 성분끼리의 곱! (Hadamard product) 각각의 곱에 대해 곱해서 값을 뱉어줌. 행렬의 곱 과는 다름.//
print(A/B)  #나누기도 마찬가지
print(B**2) #곱도 각 성분에 대해 해줌

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]

[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [90]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

print(A*B)
print(A@B)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


##numpy의 인덱싱과 슬라이싱

In [91]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [103]:
#행렬에 대한 인덱싱과 슬라이싱
A=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
print(A[0]) #0번째 행을 가져옴. 리스트 속에 리스트라고 생각해도 0번째 리스트를 가져온다고 해도 맞음
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) #<<이건 리스트에서는 안 되는거고, numpy에서만 되는 것임
B=[[1,2,3,4,],[5,6,7,8]]
print(B)
print(B[0][2])
#print(B[0,2]) #error!
print(A[1,:]) #,다음은 그 다음 디멘전을 보겠다는 뜻임. 1행, 전부이니까 위에 A[1:] 하는거랑 같은 것임.
print(A[1,0:3:2]) #0부터 3까지 2 간격.
print(A[:,2]) #전부, 2열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
[4 5 6]
[4 6]
[3 6 9]


In [121]:
#boolean 인덱싱 #numpy에서는 안 되는데 됨
a=[1,2,3,4,5,3,3] #a 안에 3을 찾고 싶음. 100으로 바꾸고 싶음
a==3 #false가 나옴. 3이라는 integer와 list
print(a==3) #여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3) #리스트와 달리 각 요소에 대해 비교해줌
A[A==3] #얘를 가지고 인덱싱을 할 수 있음. 대괄호를 썼다면 인덱싱을 하겠단 것임
print(A[A==3]) #3이 true인 지점을 indexing한다는 뜻임. True, False가 담긴 행렬로 인덱싱 가능!
#2행 4열에서 A는 3이라는 게 어디있는 지 찾아달라고 했을 때 리스트로 333이 나왔는데, 이게 무슨 의미인가요? 여기 True에 있는 값들만 데리고 온 것임
#그러니까 3 3 3 세 개가 있단 뜻일까요? 주소도 같이 물고 있음. 이걸 바꿔보면 알 수 있음

print(np.array([A[0,2],A[1,1],A[1,-1]])) # 결과값을 보여주는데, 주소를 안 보여주는 것임

A[A==3] = 100
print(A) #이걸 보면 3이 있는 값이 100으로 바뀌어 있음. 조건문과 같이 있다고 봐야함. 리스트라고 하면
#[i for i in for j in A if i==3]등.. 그런데 위에서는 조건문과 함께 들어가있어서 강력함.
#true false로 boolean indexing까지 된다는 점에서 파워풀함. 3과 같은 애를 100으로 바꿔줘.

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True,False,False,True])

A[B,:] #이 위치에 대해 True False가 있으면 그 행에 대해서 0번째 3번째 행을 가져오게 되어있음. 0행 3행 슬라이싱 할 때 쓸 수 있음. #참고로 그냥 리스트여도 됨

b=np.array([1,2,3,4])
print(b)
print(b[[True, True, False, False]]) #인덱싱 할 때 boolean으로 함.

c=[1,2,3,4]
#c[[True,True,False,False]] #error!

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[1 2 3 4]
[1 2]


In [122]:
#3차원 행렬 인덱싱
A=np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(A)
print(A.shape) #대괄호가 하나 늘마나면 왼쪽 shape 값이 추가가 된다.
print(A[0,1,2]). #여기서 왜 6이 나오지

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


#numpy의 여러 함수들

In [129]:
A=np.random.randn(3,3)
B=np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0]) #0 번째 열이 음수인 행들을 가져오는 것임


[[ 0.02084184 -0.03537606 -1.71921512]
 [ 0.223342    0.59540513  0.07884373]
 [ 0.83001831  0.56685353  0.10395138]]
[[0.4491909  0.86176647 0.92654936]
 [0.59771857 0.32397891 0.49539269]
 [0.03320396 0.26607972 0.2574436 ]]
[]


In [136]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A))) #각각에 대해 sqrt를 취함
print(np.exp(np.abs(A)))
print(np.log(np.exp(1))) #np.exp(1)=e^1
print(np.round(A)) #반올림
print(np.round(A,2))

[[ 0.54874317  1.225498   -0.36768802]
 [ 1.70244062 -0.7425555   0.85897701]
 [ 0.89565568 -0.71070889 -0.18126143]]
[[0.54874317 1.225498   0.36768802]
 [1.70244062 0.7425555  0.85897701]
 [0.89565568 0.71070889 0.18126143]]
[[0.74077201 1.10702213 0.60637284]
 [1.30477608 0.8617166  0.92681013]
 [0.94639087 0.84303552 0.42574808]]
[[1.73107597 3.40586178 1.44439134]
 [5.48732355 2.10129852 2.36074444]
 [2.44894097 2.03543364 1.19872852]]
1.0
[[ 1.  1. -0.]
 [ 2. -1.  1.]
 [ 1. -1. -0.]]
[[ 0.55  1.23 -0.37]
 [ 1.7  -0.74  0.86]
 [ 0.9  -0.71 -0.18]]


In [139]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
-0.9999999958776927


In [143]:
np.nan #not a number
#np.log(-1)
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [150]:
A=np.random.rand(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0)) #axis가 0인 부분이 축소가 된다. 3개 애들 중에서 가장 큰 것을 비교하는 것임
print(np.max(A,axis=1)) #axis가 1이면 네 개에 대해 비교를 하는 것임.
print(np.max(A,axis=0, keepdims=True))
print(np.max(A,axis=1, keepdims=True))  #마찬가지로 min에 대해서도 할 수 있음
print(np.argmax(A))
print(np.argmax(A,axis=0)) #각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A,axis=1)) #각 행에서 가장 큰 애가 존재하는 인덱스

[[0.53361916 0.27397546 0.44159263 0.84247935]
 [0.99094455 0.627521   0.81190205 0.22287396]
 [0.29239204 0.37124536 0.58796856 0.48748855]]
0.9909445515688062
[0.99094455 0.627521   0.81190205 0.84247935]
[0.84247935 0.99094455 0.58796856]
[[0.99094455 0.627521   0.81190205 0.84247935]]
[[0.84247935]
 [0.99094455]
 [0.58796856]]
4
[1 1 1 0]
[3 0 2]


In [154]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted) #오름차순으로 되어있음
print(np.flipud(a_sorted)) #내림차순으로 정리

[[ 0.16905384]
 [-0.81925873]
 [-1.65522534]
 [ 0.48832335]
 [-1.22628318]
 [ 0.33967053]]
[[-1.65522534]
 [-1.22628318]
 [-0.81925873]
 [ 0.16905384]
 [ 0.33967053]
 [ 0.48832335]]
[[ 0.48832335]
 [ 0.33967053]
 [ 0.16905384]
 [-0.81925873]
 [-1.22628318]
 [-1.65522534]]


In [157]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A,axis=1, keepdims=True)) #3행 1열짜리 2D array가 나옴
print(np.mean(A,axis=1))
print(np.mean(A,axis=1,keepdims=True))
print(np.std(A)) #standard deviation 표준 편차

[[-0.91024095  1.26468901  0.63870184  1.0035797 ]
 [ 0.64890715  1.26098678 -0.4979828  -0.60914111]
 [ 1.23296394 -0.58852729 -0.97634148  0.91507398]]
3.382668771166136
[1.9967296  0.80277001 0.58316915]
[[1.9967296 ]
 [0.80277001]
 [0.58316915]]
[0.4991824  0.2006925  0.14579229]
[[0.4991824 ]
 [0.2006925 ]
 [0.14579229]]
0.8744963911534511


In [163]:
A=np.random.randint(1,5,size=(12,)) #size(12,1,1) 하면 3차원이 됨
print(A)
#1부터 5 미만까지 랜덤하게. integer만. size만 12개.
print(A.shape)
B=A.reshape(2,2,3)
print(B) #B는 12개를 2행 3열짜리로 만들어줌. 2행 3열짜리가 두 묶음 있단 말임.
print(B.ndim) # 3 차원 행렬이다

[2 4 3 4 4 1 1 2 3 1 1 1]
(12,)
[[[2 4 3]
  [4 4 1]]

 [[1 2 3]
  [1 1 1]]]
3


In [171]:
#내적을 표현하는 여러가지 방법
a=np.array([1,2,3])
b=np.array([2,2,1])
a=a.reshape(3,1)
b=b.reshape(3,1)
#print(a@b) 하면 안 됨.
print(a.transpose()@b) #a도 b도 열벡터로 바꾼 다음. a를 transpose한 다음 곱해준 것. reshape 을 먼저 해주는 게 핵심
print(a.T@b) #T는 transpose라는 것임.

A=np.random.randn(4,3,2)
print(A.transpose(2,1,0).shape)


[[9]]
[[9]]
(2, 3, 4)


In [178]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) #4개 행이 될 수 있도록 열의 수를 맞춰라 이런 뜻임.
print(A.reshape(2,5,-1).shape)
print(A.reshape(1,-1).shape) #2차원 행 벡터를 만드는 것
print(A.reshape(-1,1).shape) #2차원 열 벡터를 만드는 것

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(1, 20)
(20, 1)


In [182]:
x=np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape) #좀 비효율적인데..
print(x[1,2,...].shape) #x[1,2,...]은 x[1,2,:,:,:] 와 같음
print(x[...,3].shape)
print(x[1,:,:,3,:].shape) # 가운데에도 들어갈 수 있는데, 생각을 할 수 있어야 채워줌

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(3, 4, 6)


In [188]:
A=np.ones((2,2))
B=np.zeros((2,2))
C=np.hstack([A,B]) #horizontal stack을 쌓는 것임
D=np.vstack([A,B])
E=np.block([A,B])
F=np.block([[A],[B]])
print(C)
print(D)
print(E)
print(F)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


In [192]:
A=np.random.randn(1,1,1,3,1,1,4,1)
#print(A)
print(A.shape)
print(A.squeeze().shape) #내가 원하는 1만 없앨 수도 있음
print(A.squeeze(axis=(0,2,4,5)).shape) #squeeze가 짜낸다는거. 0, 2, 4, 5 에 해당하는 1을 없애서 새로운 행을 만들어줌

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [204]:
A=np.random.randn(3,4)
A1 = A[np.newaxis,...]
print(A1.shape) #3,4 였는데, 1이 추가됨. 땡땡을 놨기 때문에 3,4가 땡땡에 나오고 새로운 axis가 추가된것임. np.newaixs is None <- True
A2 = A[..., np.newaxis]
print(A2.shape)
A3 = A[:,np.newaxis,:]
print(A3.shape)
A1 = np.expand_dims(A,axis=0)
print(A1.shape) #3,4 였는데, 1이 추가됨. 땡땡을 놨기 때문에 3,4가 땡땡에 나오고 새로운 axis가 추가된것임. np.newaixs is None <- True
A2 = np.expand_dims(A,axis=1)
print(A2.shape)
A3 = np.expand_dims(A,axis=2)
print(A3.shape)
A1=A.reshape(1,3,4)
print(A1.shape)
A2=A.reshape(3,4,1)
print(A2.shape)
A3=A.reshape(3,1,4)
print(A3.shape)
#어떤쪽에 많이 활용될까.. 뒤에 그림을 그릴건데, 그림을 그릴 때 차원이 안 맞으면 안됨

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 1, 4)
(3, 4, 1)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)


In [206]:
#plt.imshow(s)
#shape = (~,~) #흑백이라면 딱 두개만. 그럴때 스퀴즈를 써줌
#(10,10) #이런 데이터가 있을 때 딥러닝에 넣며거면 반드시 (1,10,10) 으로 넣하줘야함. (개수, 행, 렬) 로 들어감. 무조건 맨 앞에는 개수가 들어가야 함
#(2,3,5) #3행 5열의 2개 값이 들어감
#(10,10) -> (1,10,10) #딥러닝 할 때 shape을 오른쪽으로 바꿔주고, 이게 왼쪽으로 가는 건 squeeze, 오른쪽으로 가는 건 newaxis, expand임